guild:
  max_ally:
  max_enemies:
  create:
    max_name_size: 11
    max_tag_size: 25
    cost: 0
  invite:
    max_sync_invites: 5
    timeout_seconds: 60
  config:
    max_players: 0
    max_subleaders: 0
  cooldown:
    guild_create: 5
    change_name_or_tag: 5

message:
  tag_grande: '&cA tag da guilda deve ter no máximo {size} caracteres.'
  nome_grande: '&cO nome da guilda deve ter no máximo {size} caracteres.'
  sem_guild: '&cVocê não tem uma guilda, utilize /guild criar para criar uma.'
  cargo_insuficiente: '&cSeu cargo não é alto o suficiente.'
  ja_tem_guild: '&cVocê já está em uma guilda.'
  sem_dinheiro: '&cVocê não tem dinheiro suficiente'
  guild_criado: '&aGuilda criada com sucesso!'
  tag_existe: '&cJá existe uma guilda com a mesma tag'
  nome_existe: '&cJá existe uma guilda com o mesmo nome'
  criar_cooldown: '&cVocê deve esperar {tempo} minutos para criar outra guilda.'
  change_cooldown: '&cVocê deve esperar {tempo} minutos para mudar o nome ou tag da guilda.'
  max_convites: '&cConvites simultâneos excedidos.'
  ja_convidado: '&cO jogador já está sendo convidado por uma guilda'
  player_ja_tem_guild: '&cO jogador já está em uma guilda'
  convite_enviado: '&aConvite enviado! Ele tem {tempo} segundos para aceitar'
  no_invites: '&cNenhuma guilda está te convidando'
  max_players: '&cSua guilda atingiu o número máximo de jogadores'
  convidou_player: '&b{membro} convidou {player} para a guilda.'
  entrou_guild: '&b{membro} ingressou na guilda.'
  recusou_guild: '&b{membro} recusou o convite da guilda.'
  nao_mesmo_guild: '&cEsse jogador não está na sua guilda'
  player_kickado: '&b{membro} kickou {player} da guilda'
  foi_kickado: '&cVocê foi kickado da sua guilda'
  max_sub_liders: '&cSua guilda atingiu o número máximo de sub-líders'
  ja_mesmo_guild: '&cO jogador já está em sua guilda'
  nao_pode_promover_vc_mesmo: '&cVocê não pode promover a si mesmo'
  nao_pode_rebaixar_vc_mesmo: '&cVocê não pode rebaixar a si mesmo'
  foi_rebaixado: '&eO sub-líder {player} foi rebaixado para membro.'
  promoveu: '&b{player} promoveu {membro} para {cargo} da guilda.'
  transferiu: '&b{player} transferiu a liderança da guilda para {membro}'
  sem_confirmacao: '&cNenhuma confirmação pendente encontrada'
  lideranca_transferida: '&aLiderança transferida com sucesso!'
  ja_confirmacao: '&cVocê já tem uma confirmação pendente.'
  disband: '&eA sua ugilda foi deletada pelo líder.'
  guild_leave: '&bO jogador {player} saiu da guilda.'
  nao_esta_guild: '&cEsse jogador não está na sua guilda'
  guild_chat_message: '&b[GUILD] [{office}&b] &b{nick}&7: &e{message}'
  guild_chat_message_rank: '&b[GUILD] [{office}&b] &b[{rank}&b] &b{nick}&7: &e{message}'
  abriu_bau: '&e{player} abriu o chest da guilda.'
  abriu_bau_lider: '&e{player} abriu o báu de sub-líderes da guilda.'
  nao_pode_ser_rebaixado: '&cO jogador não pode ser rebaixado.'
  guild_disband_confirm:
    - ''
    - '&6&l[GUILD] &eVocê tem certeza? Caso você prossiga, sua guilda'
    - '           &eserá deletado, bem como todas as suas infor-.'
    - '           &emações e pontos. Para confirmar digite '
    - '           &e/guild confirmar'
    - ''
  owner_ship_confirm:
    - ''
    - '&6&l[GUILD] &eVocê tem certeza? Promovendo esse jogador você'
    - '           &eestará passando a liderança da guilda para ele.'
    - '           &ePara confirmar digite /guild confirmar'
    - ''
  no_guild_lookup:
    - ''
    - '&6&l[GUILD] &fGuilda: &6Nenhum.'
    - '  &bPeça para que te convidem para uma guilda'
    - ''
  guild_lookup:
    - ''
    - '&6&l[GUILD] &fGuilda: &6[{tag}&6] {nome}'
    - ' &6&l[GUILD] &fLíder: &b{lider}'
    - ' &6&l[GUILD] &fPontos de Guild: {pontos}'
    - ' &6&l[GUILD] &fExperiência: {exp}XP'
    - ' &6&l[GUILD] &fMembros: {membros_size} membros'
    - ' &6&l[GUILD] &fKills/Mortes totais: {kills}K/{mortes}D'
    - ' &6&l[GUILD] &fKDR: {kdr}'
    - ' &6&l[GUILD] &fComandos de Guild: &6/guild comandos'
    - ''
  guild_commands:
    - ''
    - '&6&l[GUILD] &eComandos de Guild:'
    - ' &6&l[GUILD] &f/guild criar <tag> <nome> &7- &fCria uma guilda'
    - ' &6&l[GUILD] &f/guild shop &7- &fAbre a loja da guilda'
    - ' &6&l[GUILD] &f/guild chest &7- &fAbre o chest da guilda'
    - ' &6&l[GUILD] &f/guild chest lider &7- &fAbre o chest dos lideres'
    - ' &6&l[GUILD] &f/guild home &7- &fTeleporta à home da guilda'
    - ' &6&l[GUILD] &f/guild sethome &7- &fMarca a home da guilda'
    - ' &6&l[GUILD] &f/guild kick &7- &fExpulsa alguém da guilda'
    - ' &6&l[GUILD] &f/guild tag <novaTag> &7- &fAltera a tag da guilda'
    - ' &6&l[GUILD] &f/guild nome <novoNome> &7- &fAltera o nome da guilda'
    - ' &6&l[GUILD] &f/guild membros &7- &fVer todos os membros da guilda'
    - ' &6&l[GUILD] &f/guild convidar <player> &7- &fConvida alguém pra guilda'
    - ' &6&l[GUILD] &f/guild promover <player> &7- &fPromove pra Sub-Líder'
    - ' &6&l[GUILD] &f/guild rebaixar <player> &7- &fRebaixa um Sub-Líder'
    - ' &6&l[GUILD] &f/guild setrank <player> <texto> &7- Dá rank no chat'
    - ' &6&l[GUILD] &f/guild sair &7- &fSai da guilda'
    - ' &6&l[GUILD] &f/. <texto> &7- &fEnviar mensagem pra guilda'
    - ''
  guild_membros:
    - ''
    - '&6&l[GUILD] &fMembros da sua guilda: {membros}'
    - ''
  guild_invite:
    - ''
    - ' &6&l[GUILD] &eA guild {tag} &edeseja que você faça parte deles.'
    - '         &fPara aceitar o pedido, use &2/guild aceitar&f.'
    - '         &fPara recusar o pedido, use &c/guild recusar&f.'
    - ''
  alianca_estabelecida:
    - ''
    - '&6&l[GUILD] &eSua guild agora é aliada da guilda {guild_tag}'
    - ''
